---
# tasks file for clone-git-repo

- name: ensure git is installed
  package:
    name: git
    state: present

- name: ensure .ssh directory exists
  file:
    path: "/home/{{ ansible_user }}/.ssh"
    state: directory
    mode: 0700

- name: copy SSH private key from Ansible host
  copy:
    src: "/home/{{ ansible_user }}/.ssh/{{ github_host_private_key_filename }}"
    dest: "/home/{{ ansible_user }}/.ssh/{{ github_host_private_key_filename }}"
    mode: 0600
  ignore_errors: true

- name: force clone repo
  git:
    repo: git@github.com:{{ git_username }}/{{ git_repo_name }}.git
    dest: "/home/{{ ansible_user }}/{{ git_repo_name }}"
    key_file: "/home/{{ ansible_user }}/.ssh/{{ github_host_private_key_filename }}"
    accept_hostkey: yes
    force: yes
